name: Build code

on: push

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
